<?php

use function Livewire\Volt\{title};

title('Fuhrpark - Übersicht');

?>

<x-intranet-app-fuhrpark::fuhrpark-layout heading="Fuhrpark App" subheading="Übersicht">
    {{-- Index content is automatically generated by the layout --}}
</x-intranet-app-fuhrpark::fuhrpark-layout>